name: 'Terrafrm Plan'
description: 'This action uses the `terraform plan` to generates a terraform plan. If the triggering event relates to a PR it will add a comment on the PR containing the generated plan.'
author: 'Benoit Blais'

outputs:
  ExitCode:
    description: 'Exit code for the terraform plan command'
    value: ${{ steps.BashScript.Outputs.ExitCode }}

inputs:
  Github_Token:
    description: 'GITHUB_TOKEN use to authenticate on behalf of GitHub Actions.'
    required: true
  Out_File:
    description: 'Writes the generated plan to the given filename in an opaque file format that you can later pass to terraform apply to execute the planned changes, and to some other Terraform commands that can work with saved plan files.'
    required: false

runs:
  using: "composite"
  steps:
    - id: BashScript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.Github_Token }}
        INPUT_OUT_FILE: ${{ inputs.Out_File }}
